site_name: Learning Notes
site_description: "Notes on everything I learn: system design, coding, languages, money, and people skills."
site_url: https://pratham-garg-456.github.io/learning-notes/
repo_name: pratham-garg-456/learning-notes
repo_url: https://github.com/pratham-garg-456/learning-notes
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
  font:
    text: Inter
    code: JetBrains Mono

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

nav:
  - Home: index.md
  - System Design:
      - system-design/index.md
      - Getting Started:
          - What is system design?: getting-started/what-is-system-design.md
      - Chapter I:
          - IP: chapter-1/ip.md
          - OSI Model: chapter-1/osi-model.md
          - TCP and UDP: chapter-1/tcp-and-udp.md
          - Domain Name System (DNS): chapter-1/domain-name-system-dns.md
          - Load Balancing: chapter-1/load-balancing.md
          - Clustering: chapter-1/clustering.md
          - Caching: chapter-1/caching.md
          - Content Delivery Network (CDN): chapter-1/content-delivery-network-cdn.md
          - Proxy: chapter-1/proxy.md
          - Availability: chapter-1/availability.md
          - Scalability: chapter-1/scalability.md
          - Storage: chapter-1/storage.md
      - Chapter II:
          - Databases and DBMS: chapter-2/databases-and-dbms.md
          - SQL databases: chapter-2/sql-databases.md
          - NoSQL databases: chapter-2/nosql-databases.md
          - SQL vs NoSQL databases: chapter-2/sql-vs-nosql-databases.md
          - Database Replication: chapter-2/database-replication.md
          - Indexes: chapter-2/indexes.md
          - Normalization and Denormalization: chapter-2/normalization-and-denormalization.md
          - ACID and BASE consistency models: chapter-2/acid-and-base-consistency-models.md
          - CAP Theorem: chapter-2/cap-theorem.md
          - PACELC Theorem: chapter-2/pacelc-theorem.md
          - Transactions: chapter-2/transactions.md
          - Distributed Transactions: chapter-2/distributed-transactions.md
          - Sharding: chapter-2/sharding.md
          - Consistent Hashing: chapter-2/consistent-hashing.md
          - Database Federation: chapter-2/database-federation.md
      - Chapter III:
          - N-tier architecture: chapter-3/n-tier-architecture.md
          - Message Brokers: chapter-3/message-brokers.md
          - Message Queues: chapter-3/message-queues.md
          - Publish-Subscribe: chapter-3/publish-subscribe.md
          - Enterprise Service Bus (ESB): chapter-3/enterprise-service-bus-esb.md
          - Monoliths and Microservices: chapter-3/monoliths-and-microservices.md
          - Event-Driven Architecture (EDA): chapter-3/event-driven-architecture-eda.md
          - Event Sourcing: chapter-3/event-sourcing.md
          - Command and Query Responsibility Segregation (CQRS): chapter-3/command-and-query-responsibility-segregation-cqrs.md
          - API Gateway: chapter-3/api-gateway.md
          - REST, GraphQL, gRPC: chapter-3/rest-graphql-grpc.md
          - Long polling, WebSockets, Server-Sent Events (SSE): chapter-3/long-polling-websockets-server-sent-events-sse.md
      - Chapter IV:
          - Geohashing and Quadtrees: chapter-4/geohashing-and-quadtrees.md
          - Circuit breaker: chapter-4/circuit-breaker.md
          - Rate Limiting: chapter-4/rate-limiting.md
          - Service Discovery: chapter-4/service-discovery.md
          - SLA, SLO, SLI: chapter-4/sla-slo-sli.md
          - Disaster recovery: chapter-4/disaster-recovery.md
          - Virtual Machines (VMs) and Containers: chapter-4/virtual-machines-vms-and-containers.md
          - OAuth 2.0 and OpenID Connect (OIDC): chapter-4/oauth-2-0-and-openid-connect-oidc.md
          - Single Sign-On (SSO): chapter-4/single-sign-on-sso.md
          - SSL, TLS, mTLS: chapter-4/ssl-tls-mtls.md
      - Chapter V:
          - System Design Interviews: chapter-5/system-design-interviews.md
          - URL Shortener: chapter-5/url-shortener.md
          - WhatsApp: chapter-5/whatsapp.md
          - Twitter: chapter-5/twitter.md
          - Netflix: chapter-5/netflix.md
          - Uber: chapter-5/uber.md
  - Programming:
      - Overview: coding/index.md
      - C++:
          - coding/cpp/index.md
          - Basics: coding/cpp/basics.md
          - Primitive Data Types: coding/cpp/primitive-data-types.md
          - Variables and Constants: coding/cpp/variables-and-constants.md
          - Control Structures: coding/cpp/control-structures.md
          - Pointers: coding/cpp/pointers.md
          - Classes and Objects: coding/cpp/classes-and-objects.md
          - Constructors and Destructors: coding/cpp/constructors-and-destructors.md
          - Exceptions: coding/cpp/exceptions.md
          - Smart Pointers: coding/cpp/smart-pointers.md
          - RAII: coding/cpp/raii.md
          - Pre-processor Directives: coding/cpp/pre-processor-directives.md
          - Multithreading: coding/cpp/multithreading.md
          - Thread Class: coding/cpp/thread-class.md
          - Future Library: coding/cpp/future-library.md
          - Thread Local Storage: coding/cpp/thread-local-storage.md
          - The string Library: coding/cpp/string-library.md
          - iomanip: coding/cpp/iomanip.md
          - Algorithms: coding/cpp/algorithms.md
          - STL Good Practice: coding/cpp/stl-good-practice.md
      - JavaScript:
          - coding/javascript/index.md
          - History of Browsing: coding/javascript/history-of-the-browser.md
          - Variables: coding/javascript/variables.md
          - Data Types: coding/javascript/data-types.md
          - Arrays: coding/javascript/arrays.md
          - Sets: coding/javascript/sets.md
      - Python:
          - coding/python/index.md
          - Dictionary: coding/python/dictionary.md
      - Flutter: coding/flutter.md
  - Web & Cloud:
      - Web Development:
          - coding/web/index.md
          - React:
              - coding/web/react/index.md
              - JSX: coding/web/react/jsx.md
              - Components: coding/web/react/components.md
              - Events: coding/web/react/events.md
              - Props: coding/web/react/props.md
              - Hooks: coding/web/react/hooks.md
          - Next.js: coding/web/nextjs.md
          - JSON: coding/web/json.md
          - API: coding/web/api.md
          - NextAuth.js Client API: coding/web/nextauth-client-api.md
          - Design:
              - coding/web/design/index.md
              - Color Theory: coding/web/design/color-theory.md
              - Typography: coding/web/design/typography.md
              - User Interface Design: coding/web/design/user-interface-design.md
              - User Experience (UX) Design: coding/web/design/user-experience-design.md
      - Backend:
          - coding/backend/index.md
          - FastAPI Installation and Setup: coding/backend/fastapi-installation-and-setup.md
          - FastAPI Routes: coding/backend/fastapi-routes.md
          - HTTPS Redirect Middleware: coding/backend/https-redirect-middleware.md
          - Session Middleware: coding/backend/session-middleware.md
          - GZip Middleware: coding/backend/gzip-middleware.md
          - Advanced Route Validation: coding/backend/fastapi-advanced-route-validation.md
          - Advanced Body Validation: coding/backend/fastapi-advanced-body-validation.md
          - The yield Keyword: coding/backend/yield-keyword.md
          - Beanie: coding/backend/beanie.md
          - Supabase: coding/backend/supabase.md
      - Security:
          - coding/security/index.md
          - OAuth: coding/security/oauth.md
      - Cloud (Azure):
          - coding/cloud/index.md
          - Cloud Computing: coding/cloud/cloud-computing.md
          - Benefits of Cloud Services: coding/cloud/cloud-benefits.md
          - Cloud Service Types: coding/cloud/cloud-service-types.md
          - Core Architectural Components: coding/cloud/azure-core-architecture.md
          - Compute and Networking: coding/cloud/azure-compute-and-networking.md
          - Storage Services: coding/cloud/azure-storage.md
          - Identity, Access, and Security: coding/cloud/azure-identity-access-security.md
          - Cost Management: coding/cloud/azure-cost-management.md
      - Docker: coding/docker.md
  - AI:
      - coding/ai/index.md
      - Generative AI: coding/ai/generative-ai.md
      - How AI Uses Machine Learning: coding/ai/how-ai-uses-machine-learning.md
      - AI Models and Training: coding/ai/ai-models-and-training.md
      - AI Development Techniques: coding/ai/ai-development-techniques.md
      - Generative AI Tools: coding/ai/generative-ai-tools.md
      - Data Bias and AI Harms: coding/ai/data-bias-and-ai-harms.md
      - Prompt Engineering: coding/ai/prompt-engineering.md
      - Foundational LLMs: coding/ai/foundational-llms.md
  - IT & Work:
      - IT Fundamentals:
          - coding/it/index.md
          - Computer Architecture Overview: coding/it/computer-architecture-overview.md
          - Programs, the CPU, and the Memory: coding/it/programs-cpu-and-memory.md
          - CPU: coding/it/cpu.md
          - RAM: coding/it/ram.md
          - Motherboards: coding/it/motherboards.md
          - Power Supplies: coding/it/power-supplies.md
          - Storage: coding/it/storage.md
          - Drivers and BIOS: coding/it/bios-and-drivers.md
          - Peripherals and Ports: coding/it/peripherals-and-ports.md
          - Files and File Systems: coding/it/files-and-file-systems.md
          - Character Encoding: coding/it/character-encoding.md
      - Microsoft 365:
          - coding/microsoft-365/index.md
          - Home Ribbon: coding/microsoft-365/home-ribbon.md
          - Functions and Formulas: coding/microsoft-365/functions-and-formulas.md
          - Text Functions: coding/microsoft-365/text-functions.md
          - Lookup Function: coding/microsoft-365/lookup-function.md
          - Relative, Absolute, and Mixed References: coding/microsoft-365/relative-absolute-and-mixed-references.md
          - Flash Fill: coding/microsoft-365/flash-fill.md
          - Auto Fit Column: coding/microsoft-365/auto-fit-column.md
          - Conditional Formatting: coding/microsoft-365/conditional-formatting.md
          - Custom Sort: coding/microsoft-365/custom-sort.md
          - Find and Select: coding/microsoft-365/find-and-select.md
          - Freeze and Split: coding/microsoft-365/freeze-and-split.md
      - Agile and Scrum:
          - coding/agile/index.md
          - Agile Methodology: coding/agile/agile-methodology.md
          - Introduction to Agile: coding/agile/introduction-to-agile.md
          - History and Founding of Agile: coding/agile/history-of-agile.md
          - The 4 Core Values: coding/agile/core-values.md
          - The 12 Principles: coding/agile/twelve-principles.md
          - Other Agile Methodologies: coding/agile/other-agile-methodologies.md
          - Intro to Scrum: coding/agile/intro-to-scrum.md
          - The Five Scrum Events: coding/agile/five-scrum-events-and-timebox.md
          - Sprint Planning: coding/agile/sprint-planning.md
          - Product Backlog: coding/agile/product-backlog.md
          - User Stories: coding/agile/user-stories.md
          - Scrum Roles: coding/agile/scrum-roles.md
          - The 3 Pillars of Scrum: coding/agile/three-pillars-of-scrum.md
          - The 5 Values of Scrum: coding/agile/five-values-of-scrum.md
          - Daily Scrum and Sprint Review: coding/agile/daily-scrum-and-sprint-review.md
          - Sprint Retrospective: coding/agile/sprint-retrospective.md
          - Refine the Product Backlog: coding/agile/refine-product-backlog.md
          - Velocity and Burndown Charts: coding/agile/velocity-and-burndown-charts.md
  - Languages:
      - languages/index.md
      - IELTS: languages/ielts.md
  - Money:
      - money/index.md
  - People Skills:
      - people-skills/index.md
  - Appendix:
      - Note Template: appendix/note-template.md
      - Next Steps: appendix/next-steps.md
      - References: appendix/references.md
